version: "3"

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: gogurt
    ports: 
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080